# إصدار Docker Compose (ملاحظة: هذا السطر أصبح اختياريًا في الإصدارات الحديثة)
version: '3.8'

# تعريف الخدمات (الحاويات) التي يتكون منها المشروع
services:
  # --- خدمة الواجهة الخلفية (Backend) ---
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mzadd-backend
    working_dir: /app/backend  # <-- (الإضافة الأولى) هذا هو التعديل الأهم
    volumes:
      - ./backend:/app/backend # <-- (الإضافة الثانية) قمنا بتحديث المسار هنا ليتطابق
    networks:
      - mzadd-net

  # --- خدمة Nginx (Reverse Proxy) ---
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: mzadd-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mzadd-net
    depends_on:
      - backend
      - admin-dashboard
      - merchant-dashboard
      - bidding-interface

  # --- خدمة واجهة الأدمن ---
  admin-dashboard:
    build:
      context: ./frontend/admin-dashboard
      dockerfile: Dockerfile
    container_name: mzadd-admin-dashboard
    networks:
      - mzadd-net

  # --- خدمة واجهة التاجر ---
  merchant-dashboard:
    build:
      context: ./frontend/merchant-dashboard
      dockerfile: Dockerfile
    container_name: mzadd-merchant-dashboard
    networks:
      - mzadd-net

  # --- خدمة واجهة المزايدة ---
  bidding-interface:
    build:
      context: ./frontend/bidding-interface
      dockerfile: Dockerfile
    container_name: mzadd-bidding-interface
    networks:
      - mzadd-net

# --- تعريف الشبكة ---
networks:
  mzadd-net:
    driver: bridge

